# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-26 18:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=4386876112, on_delete=django.db.models.deletion.CASCADE, to='api.Categories'),
        ),
    ]
