# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20170928_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=4510530224, on_delete=django.db.models.deletion.CASCADE, to='api.Categories'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'In Process'), ('2', 'Paid'), ('3', 'Finished'), ('4', 'Canceled')], default=1, max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='totalPrice',
            field=models.IntegerField(default=0, editable=False, verbose_name='Цена:'),
        ),
    ]
