# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20170928_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=4342782640, on_delete=django.db.models.deletion.CASCADE, to='api.Categories'),
        ),
    ]
