# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20170928_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='category',
            field=models.ForeignKey(default=4318898864, on_delete=django.db.models.deletion.CASCADE, to='api.Categories'),
        ),
    ]
